# Generated by Django 3.2.4 on 2021-07-31 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wish', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('created_at', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wish.user')),
            ],
        ),
    ]
