# Generated by Django 3.2.4 on 2021-07-31 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wish', '0003_item_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='add_item',
            field=models.ManyToManyField(related_name='added', to='wish.User'),
        ),
    ]
