# Generated by Django 3.2.4 on 2021-08-01 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wish', '0004_item_add_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='created_at',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created', to='wish.user'),
        ),
    ]
